let complementBox = () => document.querySelector("#complement")
let reverseBox = () => document.querySelector("#reverse")
let revCompBox = () => document.querySelector("#reverse-complement")
let percentDiv = () => document.querySelector('#percent-div')
let meltingDiv = () => document.querySelector('#melting-div')

let complementBox2 = () => document.querySelector("#complement2")
let reverseBox2 = () => document.querySelector("#reverse2")
let revCompBox2 = () => document.querySelector("#reverse-complement2")
let percentDiv2 = () => document.querySelector('#percent-div2')
let meltingDiv2 = () => document.querySelector('#melting-div2')