let complementBox = () => document.querySelector("#complement")
let reverseBox = () => document.querySelector("#reverse")
let revCompBox = () => document.querySelector("#reverse-complement")
let percentDiv = () => document.querySelector('#percent-div')
let meltingDiv = () => document.querySelector('#melting-div')
let lengthDiv = () => document.querySelector('#sequence-length')
let baseInput = () =>document.querySelector('#base-input1')

let complementBox2 = () => document.querySelector("#complement2")
let reverseBox2 = () => document.querySelector("#reverse2")
let revCompBox2 = () => document.querySelector("#reverse-complement2")
let percentDiv2 = () => document.querySelector('#percent-div2')
let meltingDiv2 = () => document.querySelector('#melting-div2')
let lengthDiv2 = () => document.querySelector('#sequence-length2')
let baseInput2 = () =>document.querySelector('#base-input2')

let calculateButton = () => document.querySelector('#calculate')
let equationResult = () => document.querySelector('#eq-result')
